// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'health_tracker';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String EMAIL = 'assets/images/email.png';
  static const String FACEBOOK = 'assets/images/facebook.png';
  static const String GOOGLE = 'assets/images/google.png';
  static const String LOCK = 'assets/images/lock.png';
  static const String ON_1 = 'assets/images/on_1.png';
  static const String ON_2 = 'assets/images/on_2.png';
  static const String ON_3 = 'assets/images/on_3.png';
  static const String USER_TEXT = 'assets/images/user_text.png';
}
