// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'food_nutrition';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String HOME = 'assets/images/Home.png';
  static const String HOME_SELECTED = 'assets/images/Home_selected.png';
  static const String PROFILE_SELECTED = 'assets/images/Profile-Selected.png';
  static const String PROFILE = 'assets/images/Profile.png';
  static const String SLEEP_GRAPH = 'assets/images/Sleep-Graph.png';
  static const String BG_DOTS = 'assets/images/bg_dots.png';
  static const String CHAT_BOT = 'assets/images/chat-bot.png';
  static const String COMPLETE_PROFILE = 'assets/images/complete_profile.png';
  static const String DATE = 'assets/images/date.png';
  static const String EMAIL = 'assets/images/email.png';
  static const String FACEBOOK = 'assets/images/facebook.png';
  static const String GENDER = 'assets/images/gender.png';
  static const String GOOGLE = 'assets/images/google.png';
  static const String HIGHT = 'assets/images/hight.png';
  static const String LOCK = 'assets/images/lock.png';
  static const String ON_1 = 'assets/images/on_1.png';
  static const String ON_2 = 'assets/images/on_2.png';
  static const String ON_3 = 'assets/images/on_3.png';
  static const String USER_TEXT = 'assets/images/user_text.png';
  static const String WEIGHT = 'assets/images/weight.png';
}
